services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    ports:
       - '8080:8080'
    volumes:
      - /home/user/docker/stirlingpdf/tessdata:/usr/share/tessdata #Required for extra OCR languages
      - /home/uesr/docker/stirlingpdf/configs:/configs
#      - ./customFiles:/customFiles/ - ./logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
    restart: always
